create table if not exists public.quiz_leaderboard (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(name) between 1 and 24),
  score integer not null check (score >= 0),
  created_at timestamptz not null default now()
);

alter table public.quiz_leaderboard enable row level security;

drop policy if exists "Anyone can read leaderboard" on public.quiz_leaderboard;
create policy "Anyone can read leaderboard"
on public.quiz_leaderboard
for select
to anon, authenticated
using (true);

drop policy if exists "Anyone can insert leaderboard scores" on public.quiz_leaderboard;
create policy "Anyone can insert leaderboard scores"
on public.quiz_leaderboard
for insert
to anon, authenticated
with check (
  char_length(name) between 1 and 24
  and score >= 0
  and score <= 100
);
